### ISSUE TITLE
rendering error

### ISSUE THREAD

**Issue by wsxiya** [PandaDap2006/Pandas-Extra-Details#10]
and https://legacy.curseforge.com/minecraft/texture-packs/minecraft-reimagined resource pack，When used together, will result in all Fence Gate texture error，Other doors are normal
minecraft：1.20.1
forge：47.1.43
Panda's Extra Details：0.2

**Comment by wsxiya** [comment]
![P3 }34_15Q0O}4 H%LV$ILT](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/114494454/719abe45-30b4-4da0-a3ca-ed3f2d423726)

**Comment by wsxiya** [comment]
![$1 4%S2~U9{{V}UDC( A8{P](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/114494454/9d53912c-8c8d-48aa-9298-c5598209c182)

**Comment by PandaDap2006** [comment]
Sorry about this, the mod does sadly not work with resource pack's that changes the uv's of model's, the mod replace's the original model with a custom one made by me.
