### ISSUE TITLE
Doors can't be placed correctly 

### ISSUE THREAD

**Issue by Spydnel** [PandaDap2006/Pandas-Extra-Details#13]
In the latest version for forge 1.20.1 doors can only be placed facing north no matter which direction one faces.

**Comment by PandaDap2006** [comment]
That's weird, sorry i released this update because there has not been any updates for a while and feel like it will take a bit longer to release a full update, but it will be fixed.

**Comment by PandaDap2006** [comment]
This issue has been fixed for a version that is currently only released on my discord, here is the link if you want https://discord.gg/wjPt4vEfXb
