### ISSUE TITLE
Hinge of door is always left

### ISSUE THREAD

**Issue by MaoYan5985** [PandaDap2006/Pandas-Extra-Details#14]
![3](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/122714639/4b697fc4-f424-4a95-beb4-6d4050c4225b)
 The hinge of door is always left, no matter what material the door is.

Also, the door is always facing north. And the invisibility of doors still exists.
![1](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/122714639/8ab0b487-f2e8-4841-9120-3c8c2f25d42d)
![2](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/122714639/8e277d21-219c-4815-81e9-4118d967cbee)

Mod : extra_details-0.2+1.20-1.20.1-beta [fabric]

**Comment by PandaDap2006** [comment]
This is a mistake from me, sorry, this should be fixed for the next update that will hopefully be ready soon.

**Comment by PandaDap2006** [comment]
This issue has been fixed for a version that is currently only released on my discord, here is the link if you want https://discord.gg/wjPt4vEfXb
