### ISSUE TITLE
Trapdoor can't be pushed by piston

### ISSUE THREAD

**Issue by MaoYan5985** [PandaDap2006/Pandas-Extra-Details#15]
Trapdoor can't be pushed by piston

Installed Pandas-Extra-Details
![4](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/122714639/7de22797-4bca-4fea-80e6-ea15f7b521ce)

Removed Pandas-Extra-Details
![5](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/122714639/6bfd9786-b33e-4d42-97f6-d63d98762c7a)

Mod : extra_details-0.2+1.20-1.20.1-beta

**Comment by PandaDap2006** [comment]
This problem has been fixed for a version that is currently only released on my discord, here is the link if you want https://discord.gg/wjPt4vEfXb
