### ISSUE TITLE
fabric 1.20.1 all blocks with added animations stop rendering until interacted with when the mod is added to a prexisting world

### ISSUE THREAD

**Issue by AlmostBread** [PandaDap2006/Pandas-Extra-Details#16]
fabric 1.20.1 all blocks with added animations stop rendering until interacted with when the mod is added to a prexisting world, levers are also changed to only use the cobblestone texture when a texture pack is in use affeting levers

**Comment by PandaDap2006** [comment]
This issue has been fixed for a version that is currently only released on my discord, here is the link if you want https://discord.gg/wjPt4vEfXb

**Comment by PandaDap2006** [comment]
Sorry only the first issue is fixed.

**Comment by PandaDap2006** [comment]
This issue has been resolved in the latest update
