### ISSUE TITLE
Doors and trapdoors invisible until updated

### ISSUE THREAD

**Issue by xpopy** [PandaDap2006/Pandas-Extra-Details#2]
When loading in a multiplayer world all the doors and trapdoors are invisible, but when activating them they become visible again.

This is with only the required mods installed.

![image](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/3540971/524e9cb2-a1d1-439f-9bba-95cea3050807)

![image](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/3540971/1fc9c458-1b5b-4859-990b-33c5bee71e3e)

Cool mod though, I like it!

**Comment by MrKashew** [comment]
not sure if this is same issue or separate
![2023-07-05_22 00 11](https://github.com/PandaDap2006/Pandas-Extra-Details/assets/53996665/6447d6ca-b42d-42aa-b671-fb66753fa53b)
modded door invisible even after being updated

**Comment by PandaDap2006** [comment]
its not the smae issue but something im trying to fix to, for some reason the block entity renderer dont render on modded doors.

**Comment by PandaDap2006** [comment]
These issues are fixed on a version that is only released on my discord for now, if you want it here is a link https://discord.gg/wjPt4vEfXb
