### ISSUE TITLE
Doors place incorrectly

### ISSUE THREAD

**Issue by WenXin20** [PandaDap2006/Pandas-Extra-Details#21]
Minecraft v1.20.1
Details v0.2

Doors that are placed are always facing north with the hinge on the left, no matter which direction I face.

**Comment by Kevabunch** [comment]
I'm also having this exact issue.

**Comment by PandaDap2006** [comment]
Sorry about this, im currently updating the mod with a new rendering system, the last thing it needs is support for sodium and mods alike, if you cant wait then there is a version on my discord with this fixed.

**Comment by PandaDap2006** [comment]
This issue has been resolved in the latest version
