### ISSUE TITLE
Compatible with other mods 

### ISSUE THREAD

**Issue by Vampzula** [PandaDap2006/Pandas-Extra-Details#22]
Hi, I have a question regarding compatibility with other mods that add their doors from other materials (like Supplementaries netherite door". Last time, the doors from the mods were invisible, as were trapdoors. Your mod has potential and I hope that the idea of compatibility with other mods is in the plans

Tnx Google translate

**Comment by PandaDap2006** [comment]
Im so sorry for not responding, i want to make compatibility for all the mods that needs it but for now it will only be vanilla minecraft while i develop the mod.
