### ISSUE TITLE
Title: Game Crash: NullPointerException during Rendering Block Entity in The End

### ISSUE THREAD

**Issue by YumatanGames** [PandaDap2006/Pandas-Extra-Details#3]
The game crashes when rendering a block entity, specifically a sign, in The End dimension with Better End installed. The crash report indicates a NullPointerException at net.minecraft.class_4730.method_24145 because "$$7" is null.

To Reproduce:
The exact steps that led to this error are unclear, but it appears to be related to the rendering of a sign block entity in The End. May be an Sign from some of the wood from Better End?

Crash Report Details:

The relevant section of the crash report is as follows:

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24145(net.minecraft.class_4730, java.util.function.Function)" because "$$7" is null
at net.minecraft.class_837.method_45800(class_837.java:101)
at me.pandamods.extra_details.client.renderer.block.sign.TiltSignRenderer.method_23083(TiltSignRenderer.java:54)
at me.pandamods.extra_details.client.renderer.block.sign.TiltSignRenderer.method_3569(TiltSignRenderer.java:17)
at net.minecraft.class_824.method_23079(class_824.java:90)
at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
The error seems to originate from the TiltSignRenderer method in the Extra Details mod.

Block Entity Details:

Name: minecraft:sign // net.minecraft.class_2625
Block: Block{betterend:mossy_glowshroom_sign}[rotation=4,waterlogged=false]
Block location: World: (5127,73,4524), Section: (at 7,9,12 in 320,4,282; chunk contains blocks 5120,0,4512 to 5135,255,4527), Region: (10,8; contains chunks 320,256 to 351,287, blocks 5120,0,4096 to 5631,255,4607)
Environment:

Minecraft version: 1.20.1

Additional context:

The crash occurred in The End dimension, with the Better End mod installed, with only one player present in the world. The server type is an Integrated singleplayer server.

Full crash report with modlist:
https://mclo.gs/QXttaLE

**Comment by PandaDap2006** [comment]
I will look into it.

**Comment by PandaDap2006** [comment]
sorry but im not able to reproduce the crash, it dosen't seam to be BetterEnd, Sodium or Extra Details that is the cause, if you maybe could test just with these 3 mods to see if it still happens for you then it would be nice.

**Comment by PandaDap2006** [comment]
Im closing this since there has been no response since last time i commented.
